import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { dehydrate, QueryClient, useQuery } from 'react-query';
import { getSpaceXData } from '../api';
import Image from 'next/image';

export default function Home() {
	// this query is now fetching the pre-fetched cached data from your getStaticProps()
	const { data, isLoading } = useQuery('spacex', getSpaceXData, {
		refetchOnWindowFocus: false
	});

	console.log(isLoading);

	// isLoading && <p>Loading...</p>;

	// error && <p>Error!</p>;

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					NextJs React Query with Dehydrated State
				</h1>

				<br />
				<h2>{data?.name}</h2>

				<Image
					src={data.links.patch.large}
					alt="patch-image"
					width={500}
					height={500}
					priority
				/>
			</main>
		</div>
	);
}

export const getStaticProps = async () => {
	const queryClient = new QueryClient();

	// prefetch the data
	await queryClient.prefetchQuery('spacex', getSpaceXData);

	// console.log(pageData);

	return {
		props: {
			// dehydrate the getSpaceXData API inside queryClient
			dehydratedState: dehydrate(queryClient)
		}
	};
};
